### ISSUE TITLE
No such file or directory when installing

### ISSUE THREAD

**Issue by rdiazjr** [calvin-sykes/cython_parallel_sort#1]
I always get this error when I try installing it using pip:
parallel_sort/parallel_sort.cpp(807): fatal error C1083: Cannot open include file: 'parallel/algorithm': No such file or directory

**Comment by calvin-sykes** [comment]
What's your compiler? This will only work if you are using gcc with the GNU libstdc++ which has the [Parallel Mode](https://gcc.gnu.org/onlinedocs/libstdc++/manual/parallel_mode.html).

**Comment by calvin-sykes** [comment]
I've published a new version of the package which favours using the built-in support for parallelisation in C++17. As long as your compiler is recent enough to support that standard, it should work now without needing the extra library.
